services:
  db:
    image: mysql:8.0
    container_name: gp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-gumrukplus}
      MYSQL_USER: ${DB_USER:-gumrukplus}
      MYSQL_PASSWORD: ${DB_PASSWORD:-gumrukplus}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.9-php8.2-apache
    container_name: gp_wordpress
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-gumrukplus}
      WORDPRESS_DB_USER: ${DB_USER:-gumrukplus}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-gumrukplus}
      WORDPRESS_DEBUG: 1
    volumes:
      - wp_core:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8082:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gp_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

volumes:
  db_data:
  wp_core:
